### ISSUE TITLE
Support Buiding data, Phase1

### ISSUE THREAD

**Issue by daisuke201** [sony/mapray-js#128]
## Background
It will support the feature to store and render large scale data, such as city data, and access attributes interactively. Although the source data will be assumed to be CityGML and 3D Tiles, the data handled natively by maprayJS is in a fast data format unique to Mapray.
The implementation is divided into two phases.
The first phase deals with a simple model without texture.

**Comment by veikkoeeva** [comment]
@daisuke201 Very interesting! Does this mean there will be support also IFC data?

Though my memory may fail me, I think there is a case in EU for IFC <-> CityGML and a lot of building data is open source, so it would make a very interesting case.

**Comment by daisuke201** [comment]
@veikkoeeva Thank you for your comment! and your comment is useful for us.
Currently, we are researching IFU format because we would like to support them in the feature version.
CityGML3.0 has already supported IFU.
However, we need the time to support IFC because IFU format is huge and complex so we should design the architecture both client and server side.
We will be not able to support IFC in the first version of building implementation but we are considering it!

**Comment by daisuke201** [comment]
The implementation for Phase1 has completed. 
We name building data in mapray as b3dtiles.
This version stay in branch and we plane to back to main branch to finish phase2 supprot(#177 )

User can get the b3dtiles from next version Mapray Cloud.
Next version Mapray Cloud will release in next week.
User of Mapray Cloud will be able to convert bedtiles when upload CityGML.
