### ISSUE TITLE
Simplify build output formats

### ISSUE THREAD

**Issue by daisuke201** [sony/mapray-js#270]
## Background
Currently, the project is converting TypeScript to ES modules, ES odules for the browser, and UMD, but it is becoming complex to manage. In particular, it is cumbersome to differentiate ES modules.

To simplify the build process, it is necessary to review the output format and determine which ones to prioritize. This will help to reduce the complexity of the project and make it more manageable.

**Comment by masa-sony** [comment]
- 1c0cb0744463a1407bbe506a8a568b0b2f588e0e ~ 94f274c6f059fa3604267308de7ad7ce5152f731
