### ISSUE TITLE
Upgrade to rollup 3 and update typescript version

### ISSUE THREAD

**Issue by daisuke201** [sony/mapray-js#273]
## Background
Currently, the version of rollup.js used in the project is outdated. It is required to upgrade to the latest version of rollup.js, which is version 3. Additionally, the TypeScript version also needs to be updated to the latest one. This update is necessary to take advantage of the latest features and performance improvements in rollup.js and TypeScript.

### Details
The current version of rollup.js being used is outdated and has certain limitations, which can affect the overall performance of the project. The latest version of rollup.js, which is version 3, comes with several new features and performance improvements, making it a better option for the project.

Similarly, the current version of TypeScript used in the project is also outdated. Updating it to the latest version will provide access to the latest language features and performance improvements, and will also ensure that the project is up-to-date with the latest best practices.

Therefore, it is recommended to upgrade to rollup.js version 3 and the latest version of TypeScript to improve the overall performance and ensure the project is up-to-date.

**Comment by masa-sony** [comment]
- 1c0cb0744463a1407bbe506a8a568b0b2f588e0e ~ 94f274c6f059fa3604267308de7ad7ce5152f731
