### ISSUE TITLE
Improvement of AttributionController

### ISSUE THREAD

**Issue by daisuke201** [sony/mapray-js#274]
## Background

The current functionality of AttributionController, which provides the ability to display copyright information for map resources, is not sufficient. Therefore, we need to improve it to provide better expression. The following tasks need to be completed:

- [x] Implement a function to change the compact mode of copyright display.
- [x] Determine the type of Attribution.
- [x] Determine the default copyright information.
- [x] Add functions to edit AttributionController in the Viewer.
- [x] Implement a function to change the background color.
- [x] Implement a function to change the text color.
- [x] Edit the function for updating the container.

**Comment by masa-sony** [comment]
- c35a10ba4847dc4d2c9d3c0c90f2f1ab7d4d34ab
- 20c4b87e36eea95285ac120d873a7a59d37fa6e4
- 485ca2f4c051b7b7a341911612b1eb5a7b25b882
- ef31a723d89e47714aa957f5be0aa52f791023ce
