### ISSUE TITLE
Support loading sprite images as SDF-enabled images

### ISSUE THREAD

**Issue by ShotaMatsuzaki** [sony/mapray-js#290]
Support loading sprite images as [SDF-enabled images](https://docs.mapbox.com/help/troubleshooting/using-recolorable-images-in-mapbox-maps/#using-sdf-enabled-images) when the `sdf` field is set to true in `sprite.json` file.

Example: 

```json
{
  "airport": {
    "height": 15,
    "pixelRatio": 1,
    "width": 15,
    "x": 0,
    "y": 15,
    "sdf": true
  }
}
```

**Comment by masa-sony** [comment]
3f02c5436fa58b7ef08135d310355d4a7efa059b
