### ISSUE TITLE
Proposal to implement Linter for code quality enhancement

### ISSUE THREAD

**Issue by sc-onishi** [sony/mapray-js#291]
Background:
Currently, our codebase undergoes maintenance and the addition of new features. However, proper code quality management practices have yet to be established. To automate code formatting consistency and error checking, the implementation of a linter tool is being considered.

Objective:
This issue proposes the adoption of a linter tool to improve code quality and seeks feedback and discussion on its implementation.

**Comment by masa-sony** [comment]
- e42a2ae12f2e866eaeea276778419c2c1925d98a
- 55efe3703ba3369528a37536a37ff37c35c1aa6c
- 0c6da468839044b5f18f3270f59caf78097e4021
