### ISSUE TITLE
Addition of functionality to AttributionController

### ISSUE THREAD

**Issue by sc-onishi** [sony/mapray-js#294]
Addition of functionality to AttributionController

Overview:
This issue is for adding new functionality to the AttributionController.

Background:
The current AttributionController provides management features for attributing data, identifying origins, and sources of influence. However, there's a lack of flexibility to cater to specific scenarios and needs. Adding new functionality is expected to address a broader range of use cases and enhance its value.

**Comment by masa-sony** [comment]
- c35a10ba4847dc4d2c9d3c0c90f2f1ab7d4d34ab
- 20c4b87e36eea95285ac120d873a7a59d37fa6e4
- 485ca2f4c051b7b7a341911612b1eb5a7b25b882
- ef31a723d89e47714aa957f5be0aa52f791023ce

**Comment by masa-sony** [comment]
This issue is duplicated
